# Generated by Django 4.2.16 on 2024-11-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedOrNot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=70)),
                ('time', models.CharField(max_length=70)),
                ('reason', models.TextField()),
            ],
        ),
    ]
