# Generated by Django 4.2.16 on 2024-11-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_confirmedornot_requestresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestresponse',
            name='date',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='requestresponse',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestresponse',
            name='time',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
