# Generated by Django 4.2.16 on 2024-11-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_requestresponse_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestresponse',
            name='title',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
